language: clojure

jdk:
  - oraclejdk8

sudo: required

cache:
  directories:
    - $HOME/.m2

before_install:
- gem install sass

script:
- lein run
- mv resources/public docs/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
