language: clojure

branches:
  only:
  - source

jdk:
  - oraclejdk8

sudo: required

cache:
  directories:
    - $HOME/.m2

before_install:
- gem install sass

script:
- lein run

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  target-branch: master
  local-dir: resources/public
  on:
    branch: source
